### ISSUE TITLE
ｈｏｗ　ｔｏ　ｆｉｎｄ　ｌｏｇ　ｆｉｌｅ

### ISSUE THREAD

**Issue by whuly** [zxhio/limlog#3]
ｄｅａｒ　ａｕｔｈｏｒ：
ｉ　ｔｒｙ　ｔｏ　ｆｉｎｄ　ｌｏｇ　ｆｉｌｅ　ｉｎ　ｍｙ　ｐｒｏｊｅｃｔ　ｂｕｔ　ｉ　ｃａｎ＇ｔ． ｉ　ｕｓｅsetLogFile("./test_log_file");　ｉｎ　ｕｂｕｎｔｕ　，　ｖｓｃｏｄｅ．　ａｎｄ　ｉ　ｒａｎ　ｍｙ　ｃｏｄｅ　ｂｕｔ　ｆ－ｏｕｎｄ　ｎｏｔｈｉｎｇ．　ｉ　ｕｓｅｄ　 LOG_INFO << "hello, world!";　ｉｔ　ｃｏｕｌｄ　ｒｕｎ　ｉｎ　ｔｅｒｍｉｎａｌ．　Ｃａｎ　ｙｏｕ　ｇｉｖｅ　ｍｅ　ｓｏｍｅ　ａｄｖｉｃｅ？　ｔｈａｎｋｓ．

**Comment by zxhio** [comment]
You may need to read a Benchmark.cpp
