### ISSUE TITLE
多线程问题

### ISSUE THREAD

**Issue by lipan465** [zxhio/limlog#4]
`  BlockingBuffer *blockingBuffer() {
    static thread_local BlockingBuffer *buf = nullptr;
    if (!buf) {
      std::lock_guard<std::mutex> lock(bufferMutex_);
      buf = static_cast<BlockingBuffer *>(malloc(sizeof(BlockingBuffer)));
      threadBuffers_.push_back(buf);
    }
    return buf;
  }`

 threadBuffers_.push_back(buf);这里不加锁不会有问题吗

**Comment by zxhio** [comment]
static thread_local 两个关键字，不需要加锁了
