### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by lipan465** [zxhio/limlog#5]
void setWriter(std::unique_ptr<Writer> w) { writer_.swap(w); }这里不加锁不会有问题吗？
感觉在线程启动之前设置Writer比较好。最好writer_搞个数组，支持多个Writer。同时写文件和输出控制台

**Comment by zxhio** [comment]
陆续收到了几个类似的问题了，我觉得 golang 的 logrus 实现的很好；它把 Write 和整个日志库做了分离，让用户自己去实现 Write；如果我会更新这个 Log 库，应该也是这样的思路；
