### ISSUE TITLE
有多个日志实例

### ISSUE THREAD

**Issue by qytz** [zxhio/limlog#6]
https://github.com/zxhio/limlog/blob/30b6ccb8f4a9eaf483d84d97ef266cee89ffd7be/limlog.h#L541-L544

静态局部变量只会在第一次调用函数时初始化。如果头文件中的静态函数在多个源文件中被包含，每个源文件中的静态局部变量都会被独立初始化。

在 Arch Linux 环境（g++ (GCC) 14.1.1 20240522）测试了下，看起来每个C++源文件都是一个单独的日志实例。

**Comment by zxhio** [comment]
我看了一下代码，是有这个问题；

**Comment by qytz** [comment]
我试了下，改成全局静态变量是可以的

**Comment by zxhio** [comment]
https://github.com/zxhio/limlog/commit/8a411683cc276839edf16875d48e55ca31ddd7ab  代码修改了
